# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - proshop-mern

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_942f75da1c6e411984d19363e8624c39 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4f23f47a4e6c4e90b9bbee3eb804574c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_942f75da1c6e411984d19363e8624c39 }}/proshop-v2:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'proshop-mern'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_75006f9dce1b45ff949898b874efb30b }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_942f75da1c6e411984d19363e8624c39 }}/proshop-v2:${{ github.sha }}'